"""Factorized backprojection on an NVIDIA GPU with CUDA kernels (CuPy RawKernel), the counterpart of the Pallas TPU
kernels in `pallas_ffbp.py`. Same plan, filters, geometry and arithmetic order as `ffbp2.make_ffbp`; only the
execution differs:

  * rot_fir_k: one block per (parent, pulse, 128 output columns); the input window is loaded to shared memory once,
    then for every child it is rotated by the child's phase ramp and filtered along frequency with the decimation
    filter as a direct FIR (L taps per output) instead of a matrix product. Nothing rotated reaches global memory.
  * fir_p: the pulse-axis decimation as a direct FIR over the stored children.
  * final_tile: one block of T x T threads per output tile. The two phase ramps are generated by a complex
    recurrence along frequency into shared memory (32 + 32 rows per pulse instead of one per pixel) and each thread
    accumulates its pixel's sum over pulses and frequencies with four fused multiply-adds per sample.

All arithmetic is float32 with float64 geometry on the host and, for the device levels, in CuPy float64.
"""
import math

import numpy as np
import cupy as cp

from .ffbp import C, _positions
from .ffbp2 import HOST_LEVELS, make_plan, collection_arrays  # noqa: F401  (re-exported for callers)

_SRC = r'''
#define PB 32          /* pulses per block in rot_fir_k */
#define JT 8           /* threads per pulse, each two consecutive outputs: 16 columns per block */
extern "C" __global__
void rot_fir_k(const float* __restrict__ sre, const float* __restrict__ sim, const float* __restrict__ c0, const float* __restrict__ sl,
               const float* __restrict__ taps, float* __restrict__ yre, float* __restrict__ yim,
               int C_, int P, int K, int Ko, int D, int L, int pl, float kc)
{
    // grid: x = blocks of 2 JT output columns, y = blocks of PB pulses, z = parent; block = PB * JT threads
    // thread (pp, jt): pulse p0 + pp, outputs j0 + 2 jt and j0 + 2 jt + 1. Consecutive threads are consecutive
    // pulses, so shared-memory rows (odd stride) are read without bank conflicts.
    const int j0 = blockIdx.x * (2 * JT), p0 = blockIdx.y * PB, n = blockIdx.z, tid = threadIdx.x;
    const int pp = tid % PB, jt = tid / PB;
    const int W = 2 * JT * D + L;                       // window per pulse
    const int WS = W | 1;                               // odd row stride
    const int kstart = D * j0 - pl;
    extern __shared__ float sm[];
    float* zr = sm; float* zi = sm + PB * WS; float* tp = sm + 2 * PB * WS;
    float* otr = tp + L; float* oti = otr + PB * 2 * JT;   // output tile [PB][2 JT], written out row-contiguous
    for (int r = tid; r < L; r += PB * JT) tp[r] = taps[r];
    const int p = p0 + pp;
    const bool pok = p < P;
    const float* sr = sre + ((size_t)n * P + (pok ? p : 0)) * K;
    const float* si = sim + ((size_t)n * P + (pok ? p : 0)) * K;
    const int j = j0 + 2 * jt;
    // the raw window, loaded once with consecutive threads on consecutive columns (coalesced)
    for (int idx = tid; idx < PB * W; idx += PB * JT) {
        const int row = idx / W, i = idx % W, k = kstart + i, pr = p0 + row;
        const bool ok = (pr < P) && (k >= 0) && (k < K);
        zr[row * WS + i] = ok ? sre[((size_t)n * P + pr) * K + k] : 0.f;
        zi[row * WS + i] = ok ? sim[((size_t)n * P + pr) * K + k] : 0.f;
    }
    __syncthreads();
    float prev_cc = 0.f, prev_ss = 0.f;
    for (int c = 0; c < C_; ++c) {
        // rotate the window in place by the ramp of child c relative to child c - 1 (one sine and cosine per sample
        // and child, as before, but no second copy of the window); threads along columns, so the rows differ per
        // warp only through the ramp coefficients
        const float cc = pok ? c0[((size_t)n * C_ + c) * P + p] : 0.f;
        const float ss = pok ? sl[((size_t)n * C_ + c) * P + p] : 0.f;
        {
            // this thread's samples are JT columns apart, so their phase steps are constant: one sine and cosine for
            // the first sample and one for the step, then a complex multiplication per sample (a geometric sequence)
            const float dcc = cc - prev_cc, dss = ss - prev_ss;
            float cyc = dcc + ((float)(kstart + jt) - kc) * dss;
            cyc -= rintf(cyc);
            float st = (float)JT * dss;
            st -= rintf(st);
            float wi_, wr_, si_, sr_;
            sincospif(2.0f * cyc, &wi_, &wr_);
            sincospif(2.0f * st, &si_, &sr_);
            for (int i = jt; i < W; i += JT) {
                const float vr = zr[pp * WS + i], vi = zi[pp * WS + i];
                zr[pp * WS + i] = vr * wr_ - vi * wi_;
                zi[pp * WS + i] = vr * wi_ + vi * wr_;
                const float nr = wr_ * sr_ - wi_ * si_;
                wi_ = wr_ * si_ + wi_ * sr_; wr_ = nr;
            }
            prev_cc = cc; prev_ss = ss;
        }
        __syncthreads();
        {
            float a0r = 0.f, a0i = 0.f, a1r = 0.f, a1i = 0.f;
            const float* row_r = zr + pp * WS + 2 * jt * D;
            const float* row_i = zi + pp * WS + 2 * jt * D;
            for (int r = 0; r < D; ++r) {                 // taps only the first output uses
                const float t = tp[r];
                a0r = fmaf(t, row_r[r], a0r); a0i = fmaf(t, row_i[r], a0i);
            }
            for (int r = D; r < L; ++r) {                 // shared samples
                const float vr = row_r[r], vi = row_i[r];
                const float t0 = tp[r], t1 = tp[r - D];
                a0r = fmaf(t0, vr, a0r); a0i = fmaf(t0, vi, a0i);
                a1r = fmaf(t1, vr, a1r); a1i = fmaf(t1, vi, a1i);
            }
            for (int r = L; r < L + D; ++r) {             // taps only the second output uses
                const float t = tp[r - D];
                a1r = fmaf(t, row_r[r], a1r); a1i = fmaf(t, row_i[r], a1i);
            }
            otr[pp * (2 * JT) + 2 * jt] = a0r; oti[pp * (2 * JT) + 2 * jt] = a0i;
            otr[pp * (2 * JT) + 2 * jt + 1] = a1r; oti[pp * (2 * JT) + 2 * jt + 1] = a1i;
        }
        __syncthreads();
        // coalesced store: consecutive threads write consecutive columns of one pulse's row
        for (int idx = tid; idx < PB * 2 * JT; idx += PB * JT) {
            const int row = idx / (2 * JT), col = idx % (2 * JT), pr = p0 + row, jj = j0 + col;
            if (pr < P && jj < Ko) {
                const size_t o = (((size_t)n * C_ + c) * P + pr) * (size_t)Ko + jj;
                yre[o] = otr[idx]; yim[o] = oti[idx];
            }
        }
        __syncthreads();
    }
}

#define FP_COLS 64     /* columns per block in fir_p */
extern "C" __global__
void fir_p(const float* __restrict__ yre, const float* __restrict__ yim, const float* __restrict__ taps,
           float* __restrict__ zre, float* __restrict__ zim, int P, int Ko, int Po, int D, int L, int pl, int nout)
{
    // grid: x = blocks of FP_COLS columns, y = blocks of nout output pulses, z = child; block = FP_COLS * 4 threads,
    // each thread nout / 4 of the outputs of its column. The input rows the block needs sit in shared memory
    // (nout is chosen by the caller so that they fit).
    const int j = blockIdx.x * FP_COLS + threadIdx.x % FP_COLS, i0 = blockIdx.y * nout, b = blockIdx.z, q = threadIdx.x / FP_COLS;
    const int rows = (nout - 1) * D + L;
    extern __shared__ float sm[];
    float* tr_ = sm; float* ti_ = sm + rows * FP_COLS; float* tp = sm + 2 * rows * FP_COLS;
    const float* yr = yre + (size_t)b * P * Ko;
    const float* yi = yim + (size_t)b * P * Ko;
    const int pstart = D * i0 - pl;
    for (int r = q; r < rows; r += 4) {
        const int p = pstart + r;
        const bool ok = (p >= 0) && (p < P) && (j < Ko);
        tr_[r * FP_COLS + threadIdx.x % FP_COLS] = ok ? yr[(size_t)p * Ko + j] : 0.f;
        ti_[r * FP_COLS + threadIdx.x % FP_COLS] = ok ? yi[(size_t)p * Ko + j] : 0.f;
    }
    for (int r = threadIdx.x; r < L; r += FP_COLS * 4) tp[r] = taps[r];
    __syncthreads();
    if (j >= Ko) return;
    const int col = threadIdx.x % FP_COLS;
    for (int m = 0; m < nout / 4; ++m) {
        const int io = q * (nout / 4) + m;                // local output index
        const int i = i0 + io;
        if (i >= Po) break;
        float ar = 0.f, ai = 0.f;
        const float* cr = tr_ + (io * D) * FP_COLS + col;
        const float* ci = ti_ + (io * D) * FP_COLS + col;
        for (int r = 0; r < L; ++r) {
            const float t = tp[r];
            ar = fmaf(t, cr[r * FP_COLS], ar);
            ai = fmaf(t, ci[r * FP_COLS], ai);
        }
        const size_t o = ((size_t)b * Po + i) * (size_t)Ko + j;
        zre[o] = ar; zim[o] = ai;
    }
}

extern "C" __global__
void final_tile(const float* __restrict__ dre, const float* __restrict__ dim, const float* __restrict__ ux, const float* __restrict__ uy,
                const float* __restrict__ dlx, const float* __restrict__ dly, float* __restrict__ ore, float* __restrict__ oim,
                int Pf, int Qf, int T, float a0, float a1, int pps)
{
    // grid: x = tile; block = T * T / 8 threads, each a 4 (x) by 2 (y) block of pixels. Tables for pps pulses per sync.
    const int b = blockIdx.x, tid = threadIdx.x, HX = T / 4, tx = tid % HX, ty = tid / HX;
    extern __shared__ float2 sm2[];
    const int rowlen = pps * Qf;                          // pps pulses side by side
    float2* A2 = sm2; float2* B2 = sm2 + T * rowlen;      // (re, im) pairs: one 8-byte load per complex table entry
    const float* dr = dre + (size_t)b * Pf * Qf;
    const float* di = dim + (size_t)b * Pf * Qf;
    float acc_r[4][2], acc_i[4][2];
    #pragma unroll
    for (int u = 0; u < 4; ++u) { acc_r[u][0] = acc_r[u][1] = acc_i[u][0] = acc_i[u][1] = 0.f; }
    const int nthr = (T * T) / 8;
    const int nseg = nthr / (2 * T);                      // threads per table row
    const int row = tid / nseg, seg = tid % nseg;
    const int qlen = (rowlen + nseg - 1) / nseg;
    const int qa = seg * qlen, qb = min(rowlen, qa + qlen);
    for (int p0 = 0; p0 < Pf; p0 += pps) {
        {
            const bool isA = row < T;
            const int tr = isA ? row : row - T;
            float2* R2 = (isA ? A2 : B2) + tr * rowlen;
            // segment [qa, qb) of the row: entries q < Qf belong to pulse p0, the rest to the following pulses
            int q = qa;
            while (q < qb) {
                const int ph = q / Qf, p = p0 + ph, qq = q - ph * Qf;
                const int qend = min(qb, (ph + 1) * Qf);
                const bool pok = p < Pf;
                const float g = pok ? (isA ? ux[b * Pf + p] * dlx[tr] : uy[b * Pf + p] * dly[tr]) : 0.f;
                float cyc0 = -(g * (a0 + a1 * (float)qq)); cyc0 -= rintf(cyc0);
                float cs = -(g * a1); cs -= rintf(cs);
                float wr, wi, sr, si_;
                sincospif(2.0f * cyc0, &wi, &wr);
                sincospif(2.0f * cs, &si_, &sr);
                for (; q < qend; ++q) {
                    const int qq2 = q - ph * Qf;
                    if (isA) {
                        const float d_r = pok ? dr[p * Qf + qq2] : 0.f, d_i = pok ? di[p * Qf + qq2] : 0.f;
                        R2[q] = make_float2(d_r * wr - d_i * wi, d_r * wi + d_i * wr);
                    } else {
                        R2[q] = make_float2(wr, wi);
                    }
                    const float nr = wr * sr - wi * si_;
                    wi = wr * si_ + wi * sr; wr = nr;
                }
            }
        }
        __syncthreads();
        const float2* a0 = A2 + (4 * tx) * rowlen;
        const float2* b0 = B2 + (2 * ty) * rowlen;
        #pragma unroll 2
        for (int q = 0; q < rowlen; ++q) {
            const float2 y0 = b0[q], y1 = b0[rowlen + q];
            const float y0r = y0.x, y0i = y0.y, y1r = y1.x, y1i = y1.y;
            #pragma unroll
            for (int u = 0; u < 4; ++u) {
                const float2 x = a0[u * rowlen + q];
                const float xr = x.x, xi = x.y;
                acc_r[u][0] = fmaf(xr, y0r, acc_r[u][0]); acc_r[u][0] = fmaf(-xi, y0i, acc_r[u][0]);
                acc_i[u][0] = fmaf(xr, y0i, acc_i[u][0]); acc_i[u][0] = fmaf(xi, y0r, acc_i[u][0]);
                acc_r[u][1] = fmaf(xr, y1r, acc_r[u][1]); acc_r[u][1] = fmaf(-xi, y1i, acc_r[u][1]);
                acc_i[u][1] = fmaf(xr, y1i, acc_i[u][1]); acc_i[u][1] = fmaf(xi, y1r, acc_i[u][1]);
            }
        }
        __syncthreads();
    }
    #pragma unroll
    for (int u = 0; u < 4; ++u) {
        const size_t o = ((size_t)b * T + 4 * tx + u) * T + 2 * ty;
        ore[o] = acc_r[u][0]; oim[o] = acc_i[u][0]; ore[o + 1] = acc_r[u][1]; oim[o + 1] = acc_i[u][1];
    }
}
'''

_mod = None


def _kernels():
    global _mod
    if _mod is None:
        _mod = cp.RawModule(code=_SRC, options=('--std=c++14', '--use_fast_math'))
    out = {k: _mod.get_function(k) for k in ('rot_fir_k', 'fir_p', 'final_tile')}
    for k in out.values():
        k.max_dynamic_shared_size_bytes = 96 * 1024          # opt in to more than 48 KB of shared memory per block
    return out


def _children(kern, pre, pim, c0, sl, lv):
    """pre, pim [Np, P, K] float32 (device); c0, sl [Np, C, P] float32 (device) -> [Np C, Po, Ko] planes."""
    Np, P, K = pre.shape
    Cn, Ko, Po, Dk, Dp = c0.shape[1], lv['Ko'], lv['Po'], lv['Dk'], lv['Dp']
    kc = (K - 1) / 2.0
    t0 = _tick()
    if Dk > 1:
        fk = lv['fir_k']
        taps = cp.asarray(fk['kern'], cp.float32)
        L, pl = fk['L'], fk['pl']
        yre = cp.empty((Np * Cn, P, Ko), cp.float32)
        yim = cp.empty((Np * Cn, P, Ko), cp.float32)
        W = 16 * Dk + L
        smem = (2 * 32 * (W | 1) + L + 2 * 32 * 16) * 4
        assert smem <= 96 * 1024, (Dk, L)
        kern['rot_fir_k'](((Ko + 15) // 16, (P + 31) // 32, Np), (256,),
                          (pre, pim, c0, sl, taps, yre, yim, np.int32(Cn), np.int32(P), np.int32(K), np.int32(Ko), np.int32(Dk),
                           np.int32(L), np.int32(pl), np.float32(kc)), shared_mem=smem)
    else:
        # no frequency decimation at this level: rotate only (rare; D = 1 keeps the matrix the identity)
        k = cp.arange(K, dtype=cp.float32) - np.float32(kc)
        cyc = c0[:, :, :, None] + k[None, None, None, :] * sl[:, :, :, None]
        ang = (cyc - cp.rint(cyc)) * (2 * np.pi)
        cs, sn = cp.cos(ang), cp.sin(ang)
        yre = (pre[:, None] * cs - pim[:, None] * sn).reshape(Np * Cn, P, K)
        yim = (pre[:, None] * sn + pim[:, None] * cs).reshape(Np * Cn, P, K)
    _mark('rot_fir_k', t0)
    t0 = _tick()
    if Dp > 1:
        fp = lv['fir_p']
        taps = cp.asarray(fp['kern'], cp.float32)
        zre = cp.empty((Np * Cn, Po, Ko), cp.float32)
        zim = cp.empty((Np * Cn, Po, Ko), cp.float32)
        nout = 16                                        # outputs per block: the input rows must fit in 40 KB
        while nout > 4 and (2 * ((nout - 1) * Dp + fp['L']) * 64 + fp['L']) * 4 > 40 * 1024:
            nout -= 4
        rows = (nout - 1) * Dp + fp['L']
        kern['fir_p'](((Ko + 63) // 64, (Po + nout - 1) // nout, Np * Cn), (256,),
                      (yre, yim, taps, zre, zim, np.int32(P), np.int32(Ko), np.int32(Po), np.int32(Dp), np.int32(fp['L']), np.int32(fp['pl']), np.int32(nout)),
                      shared_mem=(2 * rows * 64 + fp['L']) * 4)
        _mark('fir_p', t0)
        return zre, zim
    return yre, yim


def _device_phases(la, refs, lv):
    """Band-centre phase and slope of every child of every parent (float64 on the device): refs [Np, 3] ->
    c0, slope [Np, C, P] float32. Same formula as ffbp2.device_phases."""
    k0c = 2.0 * (lv['f0'] + (lv['K'] - 1) / 2.0 * lv['df']) / C
    k1 = 2.0 * lv['df'] / C
    u, r0, d = la['u'], la['r0'], la['d']                                   # [P, 3], [P], [C, 3] float64 device
    uc = refs @ u.T                                                          # [Np, P]
    wn = r0[None, :] * cp.sqrt(1 + ((refs * refs).sum(1)[:, None] - 2 * r0[None, :] * uc) / (r0 * r0)[None, :])
    ud = d @ u.T                                                             # [C, P]
    wd = r0[None, None, :] * ud[None] - (d[None, :, :] * refs[:, None, :]).sum(2)[:, :, None]      # [Np, C, P]
    num = (d * d).sum(1)[None, :, None] - 2 * wd
    ddr = num / (cp.sqrt(wn[:, None, :] ** 2 + num) + wn[:, None, :])
    c0 = ddr * k0c
    return (c0 - cp.rint(c0)).astype(cp.float32), (ddr * k1).astype(cp.float32)


PROFILE = {}


def _mark(name, start):
    """Accumulate the device time since `start` (an Event) under `name` when profiling is on."""
    if PROFILE.get('on'):
        e = cp.cuda.Event(); e.record(); e.synchronize()
        PROFILE[name] = PROFILE.get(name, 0.0) + cp.cuda.get_elapsed_time(start, e) * 1e-3


def _tick():
    if PROFILE.get('on'):
        e = cp.cuda.Event(); e.record(); return e
    return None


def make_ffbp_cuda(plan, coll, final_mode='fp32'):
    """Build form(S) -> complex64 image [nx, ny] (device) for the plan and the collection arrays (host float64).
    final_mode: 'fp32' (CUDA cores, float32) or 'f16tc' (tensor cores, float16 operands, float32 accumulation)."""
    kern = _kernels()
    levels, T, L = plan['levels'], plan['T'], len(plan['levels'])
    fin = plan['final']
    Pf, Qf = fin['P'], fin['K']
    a0, a1, fc2 = 2.0 * fin['f0'] / C, 2.0 * fin['df'] / C, 2.0 * fin['fc'] / C
    e1, e2 = np.asarray(plan['e1'], np.float64), np.asarray(plan['e2'], np.float64)
    en = np.cross(e1, e2)
    dlx_h = ((np.arange(T) - (T - 1) / 2.0) * plan['spx']).astype(np.float64)
    dly_h = ((np.arange(T) - (T - 1) / 2.0) * plan['spy']).astype(np.float64)
    dlx, dly = cp.asarray(dlx_h, cp.float32), cp.asarray(dly_h, cp.float32)
    dev = []
    for i, (lv, cl) in enumerate(zip(levels, coll['levels'])):
        e = {}
        if i < HOST_LEVELS:
            e['c0'], e['slope'] = cp.asarray(cl['c0'], cp.float32), cp.asarray(cl['slope'], cp.float32)
        else:
            e.update(u=cp.asarray(cl['u']), r0=cp.asarray(cl['r0']), d=cp.asarray(lv['d']), ref=cp.asarray(lv['ref']))
        dev.append(e)
    fu, fr0 = cp.asarray(coll['final']['u']), cp.asarray(coll['final']['r0'])
    fcen = cp.asarray(fin['cen'])
    e1d, e2d, end = cp.asarray(e1), cp.asarray(e2), cp.asarray(en)
    sx0, sy0 = levels[0]['sx'], levels[0]['sy']
    G = sx0 * sy0
    mx, my = plan['Nx'] // sx0, plan['Ny'] // sy0
    shape_g = [s for lv in levels[1:] for s in (lv['sx'], lv['sy'])] + [T, T]
    perm_g = [2 * i for i in range(L - 1)] + [2 * (L - 1)] + [2 * i + 1 for i in range(L - 1)] + [2 * (L - 1) + 1]
    pps = 2 if 4 * T * (2 * Qf) * 4 <= 48 * 1024 else 1                   # pulses per table (shared memory 48 KB)
    smem_final = 4 * T * (pps * Qf) * 4
    assert T % 4 == 0 and T * T // 8 <= 1024 and (T * T // 8) % (2 * T) == 0 and smem_final <= 48 * 1024, (T, Qf)

    def final(are, aim, cen):
        """are, aim [B, Pf, Qf]; cen [B, 3] float64 -> (re, im) [B, T, T]."""
        B = are.shape[0]
        t0 = _tick()
        w = fr0[None, :, None] * fu[None, :, :] - cen[:, None, :]                       # [B, Pf, 3]
        wn = cp.sqrt((w * w).sum(2))
        ux = (w @ e1d) / wn
        uy = (w @ e2d) / wn
        uz = (w @ end) / wn
        mxv, myv, mzv = ux.mean(1), uy.mean(1), uz.mean(1)
        mn = cp.sqrt(mxv * mxv + myv * myv + mzv * mzv)
        ucx, ucy, rc = mxv / mn, myv / mn, wn.mean(1)
        ore = cp.empty((B, T, T), cp.float32)
        oim = cp.empty((B, T, T), cp.float32)
        _mark('final_geom', t0)
        t0 = _tick()
        if final_mode == 'f16tc':
            ore, oim = final_tile_tc(cp.ascontiguousarray(are), cp.ascontiguousarray(aim), cp.ascontiguousarray(ux.astype(cp.float32)),
                                     cp.ascontiguousarray(uy.astype(cp.float32)), dlx, dly, a0, a1, T)
        else:
            kern['final_tile']((B,), (T * T // 8,), (cp.ascontiguousarray(are), cp.ascontiguousarray(aim), cp.ascontiguousarray(ux.astype(cp.float32)),
                                                cp.ascontiguousarray(uy.astype(cp.float32)), dlx, dly, ore, oim,
                                                np.int32(Pf), np.int32(Qf), np.int32(T), np.float32(a0), np.float32(a1), np.int32(pps)), shared_mem=smem_final)
        _mark('final_tile', t0)
        t0 = _tick()
        dx, dy = cp.asarray(dlx_h)[None, :, None], cp.asarray(dly_h)[None, None, :]
        los = ucx[:, None, None] * dx + ucy[:, None, None] * dy
        qc = (dx * dx + dy * dy - los * los) * (fc2 / (2.0 * rc[:, None, None]))
        ang = ((qc - cp.rint(qc)) * (2 * np.pi)).astype(cp.float32)
        c, s = cp.cos(ang), cp.sin(ang)
        out = ore * c - oim * s, ore * s + oim * c
        _mark('final_corr', t0)
        return out

    def one_tile(a, b, g):
        """Level-0 child g [Po0, Ko0] through the remaining levels -> its mx x my block."""
        a, b = a[None], b[None]
        for i in range(1, L):
            lv, la = levels[i], dev[i]
            if i < HOST_LEVELS:
                c0, sl = la['c0'][g][None], la['slope'][g][None]
                a, b = _children(kern, a, b, c0, sl, lv)
            else:
                nb_par = a.shape[0]
                refs = la['ref'].reshape(G, nb_par, 3)[g]
                t0 = _tick()
                c0, sl = _device_phases(la, refs, lv)
                _mark('device_phases', t0)
                a, b = _children(kern, a, b, c0, sl, lv)
        cen = fcen.reshape(G, -1, 3)[g]
        re, im = final(a, b, cen)
        return (re.reshape(shape_g).transpose(perm_g).reshape(mx, my), im.reshape(shape_g).transpose(perm_g).reshape(mx, my))

    ox, oy, nx, ny = plan['ox'], plan['oy'], plan['nx'], plan['ny']

    def form(S, ng=8):
        """S [P, K] complex64 (host or device, already windowed) -> complex64 image [nx, ny] on the device."""
        S = cp.asarray(S)
        scale = float(cp.abs(S).max())
        pre = cp.ascontiguousarray((S.real / scale).astype(cp.float32))[None]
        pim = cp.ascontiguousarray((S.imag / scale).astype(cp.float32))[None]
        lv0, la0 = levels[0], dev[0]
        full = cp.empty((plan['Nx'], plan['Ny']), cp.complex64)
        for g0 in range(0, G, ng):
            gs = list(range(g0, min(G, g0 + ng)))
            c0 = cp.ascontiguousarray(la0['c0'][0, gs][None])
            sl = cp.ascontiguousarray(la0['slope'][0, gs][None])
            A, Bm = _children(kern, pre, pim, c0, sl, lv0)                           # [ng, Po, Ko]
            for k, g in enumerate(gs):
                re, im = one_tile(A[k], Bm[k], g)
                x, y = g // sy0, g % sy0
                full[x * mx:(x + 1) * mx, y * my:(y + 1) * my] = re + 1j * im
            del A, Bm
        return full[ox:ox + nx, oy:oy + ny] * np.float32(scale)

    return form


# ----------------------------------------------------------------------------------------------------------------------
# Tensor-core final stage: the same 2T x 2T product per tile as the XLA path, on the GPU's matrix units (wmma), with the
# ramp tables built in shared memory two pulses at a time and converted to float16 (one pass; a float32 result from
# float16 operands, the GPU's counterpart of the TPU's single bfloat16 pass).
# ----------------------------------------------------------------------------------------------------------------------
_SRC_TC = r'''
#include <mma.h>
#include <cuda_fp16.h>
using namespace nvcuda;
#define TT 32
#define PPS 2
#define NSEG 2
extern "C" __global__
void final_tile_tc(const float* __restrict__ dre, const float* __restrict__ dim, const float* __restrict__ ux, const float* __restrict__ uy,
                   const float* __restrict__ dlx, const float* __restrict__ dly, float* __restrict__ ore, float* __restrict__ oim,
                   int Pf, int Qf, float a0, float a1)
{
    // grid: x = tile; block = 512 threads (16 warps, one output fragment each). A_s and B_s: [2T][KP] half,
    // KP = PPS Qf rounded up to 16, ld = KP + 8. The tables are built by 512 threads: NSEG segments of each row.
    const int b = blockIdx.x, tid = threadIdx.x, warp = tid / 32;
    const int K2 = PPS * Qf, KP = (K2 + 15) / 16 * 16, LD = KP + 8;
    extern __shared__ __align__(32) unsigned char smraw[];
    half* A_s = reinterpret_cast<half*>(smraw);
    half* B_s = A_s + 2 * TT * LD;
    float* M_s = reinterpret_cast<float*>(smraw);                 // reused at the end: [2T][2T + 4]
    const float* dr = dre + (size_t)b * Pf * Qf;
    const float* di = dim + (size_t)b * Pf * Qf;
    // zero the padding columns once
    for (int i = tid; i < 2 * TT * (LD - K2); i += 512) {
        const int row = i / (LD - K2), col = K2 + i % (LD - K2);
        A_s[row * LD + col] = __float2half(0.f); B_s[row * LD + col] = __float2half(0.f);
    }
    wmma::fragment<wmma::accumulator, 16, 16, 16, float> acc;
    wmma::fill_fragment(acc, 0.f);
    // this warp's output fragment of the 4 x 4 grid
    const int fi = warp / 4, fj = warp % 4;
    // table building: the matrices have 2T rows each ([T real-part rows; T imag-part rows]); thread -> (table, row,
    // pulse, segment): 2 tables x 2T rows x PPS pulses x NSEG segments = 512
    const int seg = tid % NSEG;
    const int rest = tid / NSEG;
    const int which = rest / (2 * TT * PPS);                      // 0: A rows (data x ramp), 1: B rows (ramp)
    const int rem = rest % (2 * TT * PPS);
    const int row2 = rem / PPS, ph = rem % PPS;                    // row2 in 0 .. 2T-1 (first T real, next T imag)
    const int tr = row2 % TT; const bool imag = row2 >= TT;
    const int qlen = (Qf + NSEG - 1) / NSEG, qa = seg * qlen, qb = min(Qf, qa + qlen);
    for (int p0 = 0; p0 < Pf; p0 += PPS) {
        const int p = p0 + ph;
        const bool pok = p < Pf;
        const float g = pok ? (which == 0 ? ux[b * Pf + p] * dlx[tr] : uy[b * Pf + p] * dly[tr]) : 0.f;
        float cyc0 = -(g * (a0 + a1 * (float)qa)); cyc0 -= rintf(cyc0);
        float cs = -(g * a1); cs -= rintf(cs);
        float wr, wi, sr, si_;
        sincospif(2.0f * cyc0, &wi, &wr);
        sincospif(2.0f * cs, &si_, &sr);
        half* R = (which == 0 ? A_s : B_s) + row2 * LD + ph * Qf;
        for (int q = qa; q < qb; ++q) {
            float v;
            if (which == 0) {
                const float d_r = pok ? dr[p * Qf + q] : 0.f, d_i = pok ? di[p * Qf + q] : 0.f;
                v = imag ? (d_r * wi + d_i * wr) : (d_r * wr - d_i * wi);
            } else {
                v = imag ? wi : wr;
            }
            R[q] = __float2half(v);
            const float nr = wr * sr - wi * si_;
            wi = wr * si_ + wi * sr; wr = nr;
        }
        __syncthreads();
        for (int k = 0; k < KP; k += 16) {
            wmma::fragment<wmma::matrix_a, 16, 16, 16, half, wmma::row_major> fa;
            wmma::fragment<wmma::matrix_b, 16, 16, 16, half, wmma::col_major> fb;
            wmma::load_matrix_sync(fa, A_s + (fi * 16) * LD + k, LD);
            wmma::load_matrix_sync(fb, B_s + (fj * 16) * LD + k, LD);
            wmma::mma_sync(acc, fa, fb, acc);
        }
        __syncthreads();
    }
    // M = [Ar; Ai] [Br; Bi]^T : cre = M00 - M11, cim = M01 + M10
    const int LM = 2 * TT + 4;
    wmma::store_matrix_sync(M_s + (fi * 16) * LM + fj * 16, acc, LM, wmma::mem_row_major);
    __syncthreads();
    for (int i = tid; i < TT * TT; i += 512) {
        const int t = i / TT, t2 = i % TT;
        const size_t o = ((size_t)b * TT + t) * TT + t2;
        ore[o] = M_s[t * LM + t2] - M_s[(t + TT) * LM + t2 + TT];
        oim[o] = M_s[t * LM + t2 + TT] + M_s[(t + TT) * LM + t2];
    }
}
'''
_mod_tc = None


def final_tile_tc(are, aim, ux, uy, dlx, dly, a0, a1, T):
    """are, aim [B, Pf, Qf] float32; ux, uy [B, Pf]; -> (re, im) [B, T, T] via the tensor-core kernel (T must be 32)."""
    global _mod_tc
    assert T == 32
    if _mod_tc is None:
        _mod_tc = cp.RawModule(code=_SRC_TC, backend='nvcc', options=('-std=c++14', '--use_fast_math', '-arch=sm_%d%d' % cp.cuda.Device().compute_capability_tuple()
                               if hasattr(cp.cuda.Device(), 'compute_capability_tuple') else '-arch=sm_' + cp.cuda.Device().compute_capability))
    k = _mod_tc.get_function('final_tile_tc')
    B, Pf, Qf = are.shape
    K2 = 2 * Qf
    KP = (K2 + 15) // 16 * 16
    LD = KP + 8
    smem = max(2 * 2 * T * LD * 2, 2 * T * (2 * T + 4) * 4)
    ore = cp.empty((B, T, T), cp.float32)
    oim = cp.empty((B, T, T), cp.float32)
    k((B,), (512,), (are, aim, ux, uy, dlx, dly, ore, oim, np.int32(Pf), np.int32(Qf), np.float32(a0), np.float32(a1)), shared_mem=smem)
    return ore, oim
